apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my.komodo.workspace
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: resources
    repoURL: git@github.com:asaintsever/komodo-workspace.git
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
